### ISSUE TITLE
9.013.02 does not work with kernel 6.9

### ISSUE THREAD

**Issue by faptaincrunch** [awesometic/realtek-r8125-dkms#57]
Fresh Ubuntu 24.04 install. DKMS and running the autorun script fail. 

```
/home/marc/Downloads/r8125-9.013.02/src/r8125_n.c:7682:20: error: initialization of ‘int (*)(struct net_device *, struct ethtool_keee *)’ from incompatible pointer type ‘int (*)(struct net_device *, struct ethtool_eee *)’ [-Werror=incompatible-pointer-types]
 7682 |         .get_eee = rtl_ethtool_get_eee,
      |                    ^~~~~~~~~~~~~~~~~~~
```

**Comment by awesometic** [comment]
Hello. 

This is the same issue with https://github.com/awesometic/realtek-r8125-dkms/issues/56 , so I will close this issue. Please visit that page to discuss.
